# -*- coding: utf-8 -*-
"""5figuras_area.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xy-iSQuOQTxXUbvKfsgaiEcR3nhfCOUu
"""

class NombreFigura:
    def __init__(self, nombre):
        self.__nombre = nombre

    def get_nombre(self):
        return self.__nombre


class Figura:
    def __init__(self, base_menor, base_mayor, altura):
        self.__base_menor = base_menor
        self.__base_mayor = base_mayor
        self.__altura = altura

    def get_base_menor(self):
        return self.__base_menor

    def get_base_mayor(self):
        return self.__base_mayor

    def get_altura(self):
        return self.__altura

class Triangulo(NombreFigura):
    def __init__(self, base, altura):
        super().__init__("TRIANGULO")
        self._base = base
        self._altura = altura

    def get_base(self):
        return self._base

    def get_altura(self):
        return self._altura

    def calcularArea(self):
         return self._base * self._altura/2

#-----------esta seccion calcula el area del CUADRADO------------------

class Cuadrado(NombreFigura):
    def __init__(self, lado):
        super().__init__("CUADRADO")
        self.lado = lado

    def calcularArea(self):
        return self.lado ** 2

#---------esta seccion calcula el area del RECTANGULO----------------

class Rectangulo(NombreFigura):
    def __init__(self, base, altura):
        super().__init__("RECTANGULO")
        self.base = base
        self.altura = altura

    def calcularArea(self):
        return self.base * self.altura

#---------esta seccion calcula el area del ROMBO----------------
class Rombo(NombreFigura):
    def __init__(self, diagonal_mayor, diagonal_menor):
        super().__init__("ROMBO")
        self.diagonal_mayor = diagonal_mayor
        self.diagonal_menor = diagonal_menor

    def calcularArea(self):
        return self.diagonal_mayor * self.diagonal_menor/2

#---------esta seccion calcula el area del ROMBOIDE----------------
class Romboide(NombreFigura):
    def __init__(self, base, altura):
        super().__init__("ROMBOIDE")
        self.base = base
        self.altura = altura

    def calcularArea(self):
        return self.base * self.altura


class Trapecio(Figura):
    def __init__(self, base_menor, base_mayor, altura):
        super().__init__(base_menor, base_mayor, altura)

    def calcularArea(self):
        return (self.get_base_menor() + self.get_base_mayor()) * self.get_altura() / 2

class Menu:
    def mostrarMenu():
      print("bienvenido a la calculadora de areas y perimetros")



#--------este metodo permitira que  el programa se ejecute------------
    def obtener_figura(opcion):

        if opcion == 1:
            base = int(input("Ingrese la base del triangulo"))
            altura = int(input("ingrese la altura del triángulo"))
            figura = Triangulo(base, altura)
            return figura
        elif opcion == 2:
            lado = int(input("Ingrese el lado del cuadrado: "))
            return Cuadrado(lado)
        elif opcion == 3:
            base = int(input("Ingrese la base del rectángulo "))
            altura =  int(input("Ingrese la altura del rectángulo "))
            return Rectangulo(base, altura)
        elif opcion == 4:
            diagonal_mayor = int(input("Ingrese diagonal mayor del rombo"))
            diagonal_menor =  int(input("Ingrese diagonal menor del rombo"))
            return Rombo(diagonal_mayor, diagonal_menor)
        elif opcion == 5:
            base = int(input("Ingrese la base del romboide"))
            altura = int(input("Ingrese la altura del romboide"))
            return Romboide(base, altura)
        elif opcion == 6:
            base_menor = int(input("Ingrese la base menor del trapecio: "))
            base_mayor = int(input("Ingrese la base mayor del trapecio: "))
            altura = int(input("Ingrese la altura del trapecio: "))
            return Trapecio(base_menor, base_mayor, altura)
    def ejecutarPrograma():
        Menu.mostrarMenu()

        while True:

            print("1. Triángulo")
            print("2. Cuadrado")
            print("3. Rectángulo")
            print("4. Rombo")
            print("5. Romboide")
            print("6. Trapecio")
            print("0. Salir")

            opcion = int(input("Ingrese el numero de la figura ó 0 para salir"))

            if opcion == 0:
                print("hasta pronto")
                break
            if opcion <0 or opcion >6:
                print("esta no es opcion valida")
                continue


            figura = Menu.obtener_figura(opcion)
            print(f"Área de la figura es: {figura.calcularArea()}")




  # Ejecutar el programa
Menu.ejecutarPrograma()